[tool]
[tool.black]
line-length = 79
target-version = ["py38"]
[tool.poetry]
authors = ["Volatus <veritasvolatus@gmail.com>"]
description = ""
name = "python-package-manager"
version = "1.1.13"
[tool.poetry.dependencies]
"discord.py" = "1.7.3"
flask = "2.1.1"
python = "^3.8"
